export default {data:[
    {
        title:"Echo Buds",
        amount:0, 
        description:["Dynamic audio and active noise cancellation (ANC)—premium speakers deliver crisp, balanced sound. Sealed in-ear design and ANC limit background noise.", "Compact and comfortable—Echo Buds are small, light and sweat-resistant, with a customisable fit that's made to move with you.", "Hands-free entertainment—Echo Buds work with the Alexa app to stream music and play podcasts or Audible audiobooks—just ask.",  "Long-lasting battery—get up to 5 hrs’ music playback per charge and up to 15 hrs with the charging case. A quick 15-minute charge provides up to 2 hrs of music.",  "Leave your phone in your pocket—use your voice to make calls, set reminders or add items to your shopping list.",   "Works with other assistants—compatible with iOS and Android, also supports access to Siri and Google Assistant.",  "Designed to protect your privacy—built with multiple layers of privacy protection and control, including the ability to mute the microphones with the Alexa app. You can also view, hear or delete voice recordings at any time."],
        id:6654,
        image:"/echo-buds.png", 
        detailImages:[{address:"/echo-buds.png", id:1},{address:"/echo-buds-details-image-1.png", id:2},{address:"/echo-buds-details-image-2.png", id:3}
        ,{address:"/echo-buds-details-image-3.png", id:4},{address:"/echo-buds-details-image-4.png", id:5},{address:"/echo-buds-details-image-5.png", id:6}],
        reviews:[4,4,4,4], 
        reviewsAmount:"727", 
        firstPrice:"109", 
        lastPrice:"99", 
        totalPrice:109.99,
        availability:true,
        arrayNumber:0, 
    
    },
    {
        title:"Echo Dot",
        amount:0, 
        description:["Meet Echo Dot—our most popular smart speaker with Alexa. The sleek, compact design delivers crisp vocals and balanced bass for full sound.", "Voice control your entertainment—stream songs from Amazon Music, Apple Music, Spotify, Deezer and more. Play music, audiobooks and podcasts throughout your home with multi-room music." , "Supports lossless HD audio available on select streaming services such as Amazon Music HD.", "Ready to help—ask Alexa to tell a joke, play music, answer questions, play the news, check the weather, set alarms and more." , "Control your smart home—use your voice to turn on lights, adjust thermostats and lock doors with compatible devices.","Connect with others—Call almost anyone hands free. Instantly drop in on other rooms or announce to the entire household that dinner's ready." ,"Designed to protect your privacy—built with multiple layers of privacy protection and control, including a Microphone Off button that electronically disconnects the microphones."],
        id:9986, 
        image:"/alexa.png", 
        detailsImage:"/echo-dot-details-image.png",
        detailImages:[{address:"/echo-dot-details-image.png", id:1},{address:"/echo-dot-details-img-1.png", id:2},{address:"/echo-dot-details-img-2.png", id:3},{address:"/echo-dot-details-img-3.png", id:4}
        ,{address:"/echo-dot-details-img-4.png", id:5},{address:"/echo-dot-details-img-5.png", id:6},],
        reviews:[4,4,4,4,4], 
        reviewsAmount:"181,207", 
        firstPrice:"49", 
        lastPrice:"99", 
        totalPrice:"49.99",
        availability:true, 
        arrayNumber:1, 
    },
    {
        title:"Fire Tablet 7",
        amount:0, 
        description:[`7" IPS display, 16 or 32 GB of internal storage (up to 512 GB of expandable storage with microSD).`, "Faster 1.3 GHz quad-core processor and 1 GB of RAM.", "Up to 7 hours of reading, surfing the web, watching video and listening to music.", "Enjoy your favourite apps like BBC iPlayer, Netflix, Disney+, Facebook, Instagram, TikTok, YouTube and more through the Amazon Appstore (Google Play Store not supported). Subscription fees may apply.", "Now hands free with Alexa.", "2 MP rear-facing camera and HD 720p front-facing camera."],
        id:24665,
        image:"/fire-tablet.png",
        detailImages:[{address:"/fire-tabet-details-img-1.png", id:1},{address:"/fire-tabet-details-img-2.png", id:2},{address:"/fire-tabet-details-img-3.png", id:3},{address:"/fire-tabet-details-img-4.png", id:4}
        ,{address:"/fire-tabet-details-img-5.png", id:5}],
        reviews:[4,4,4,4,4], 
        reviewsAmount:"75,548", 
        firstPrice:"49", 
        lastPrice:"99", 
        totalPrice:"49.99",
        availability:true, 
    },
    {
        title:"Fire TV Stick",
        amount:0, 
        description:["Latest release of our best-selling streaming device, 50% more powerful than the previous-generation Fire TV Stick (2019 release) for fast streaming in Full HD. Includes Alexa Voice Remote with power and volume buttons.", "Less clutter, more control—Alexa Voice Remote lets you use your voice to search and launch programmes from across different apps. All new preset buttons get you to your favourite apps quickly. You can also control power and volume on your compatible TV and soundbar without needing another remote.", "Home cinema audio with support for Dolby Atmos: feel scenes come to life with immersive Dolby Atmos audio, on selected titles, with compatible home audio systems.", "Thousands of apps, Alexa skills and channels—including BBC iPlayer, Netflix, YouTube, Prime Video, Now, Disney+, ITV Hub, All 4, My5 and more. Subscription fees may apply", "Amazon Prime members get unlimited access to hundreds of thousands of films and TV episodes.", "Live TV—watch your favourite live TV, news and sport with subscriptions to Eurosport, ITV Hub, Sky News and more. Use the Guide button to see what's available and when.", "Free TV—access films and TV programmes from apps such as ITV Hub, All 4, PlutoTV, YouTube and more." ],
        id:78781,
        image:"/fire-tv.png", 
        detailImages:[{address:"/fire-tv-details-img-1.png", id:1},{address:"/fire-tv-details-img-2.png", id:2},{address:"/fire-tv-details-img-3.png", id:3}
        ,{address:"/fire-tv-details-img-4.png", id:4},{address:"/fire-tv-details-img-5.png", id:5},{address:"/fire-tv-details-img-6.png", id:6} ],
        detailsImage:"fire-tv-details.png",
        reviews:[4,4,4,4,4], 
        reviewsAmount:"39,936", 
        firstPrice:"39", 
        lastPrice:"99",
        totalPrice:"39.99", 
        availability:true, 
    },
    {
        title:"Kindle Paperwhite",
        amount:0, 
        description:[`Kindle Paperwhite: now with a 6.8" display and thinner borders, adjustable warm light, up to 10 weeks of battery life and 20% faster page turns compared to the previous generation.`, "Purpose-built for reading: with a flush-front design and 300 ppi glare-free display that reads like real paper, even in bright sunlight.", "More books in more places: store thousands of titles, then take them all with you. A single charge via USB-C last weeks, not hours.", "Easy on the eyes: now with adjustable warm light to change screen shade from white to amber." , "Waterproof (IPX8), so you’re free to read and relax at the beach, by the pool or in the bath. Your Kindle has been tested to withstand accidental immersion.","Purchase Kindle Paperwhite and get 3 months Kindle Unlimited for free. Explore millions of books, thousands of audiobooks and selected magazine subscriptions with Kindle Unlimited and read anywhere anytime." , "Go hands free: pair with an Audible subscription and Bluetooth headphones or speakers to listen to your story."],
        id:3456654,
        image:"/kindle-paperwhite.png",
        detailImages:[{address:"/kindle-paperwhite-details.png", id:1},{address:"/kindle-paperwhite-details-iimg-1.png", id:2},{address:"/kindle-paperwhite-details-iimg-2.png", id:3}
        ,{address:"/kindle-paperwhite-details-iimg-3.png", id:4},{address:"/kindle-paperwhite-details-iimg-4.png", id:5},{address:"/kindle-paperwhite-details-iimg-5.png", id:6} ],
        detailsImage:"/kindle-paperwhite-details.png", 
        reviews:[4,4,4,4], 
        reviewsAmount:"2,018", 
        firstPrice:"129", 
        lastPrice:"99",
         totalPrice:129.99,
        availability:true,
    },
    {
        title:"Echo Show 5",
        amount:0, 
        description:["See your day with Alexa at the ready: set alarms and timers, check your calendar or the news, make video calls with the 2 MP camera, and stream music or series—all with your voice.", "Add Alexa to your bedside table: ease into the day with a routine that turns compatible lights on. Wake up to your news update, the weather forecast or your favourite music.", "Manage your smart home: look in when you're away with the built-in camera. Control compatible devices like cameras, lights and more using the interactive display or your voice.", "Connect with video calling: use the 2 MP camera to call friends and family who have the Alexa app or an Echo device with a screen. Make announcements to other compatible devices in your home.", "Be entertained: ask Alexa to play TV programmes and films via Prime Video, Netflix and more. Stream favourites from Amazon Music, Apple Music, Spotify and others.", "Put photos on (smart) display: use Amazon Photos or Facebook to turn your Home screen into a digital frame.", "Designed to protect your privacy: electronically disconnect the microphones and camera with the press of a button. Slide the built-in cover to close the camera. "],
        id:34522,
        image:"/echo-show-5.png", 
        detailImages:[{address:"/echo-show-5-details-img-1.png", id:1},{address:"/echo-show-5-details-img-2.png", id:2},{address:"/echo-show-5-details-img-3.png", id:3}
        ,{address:"/echo-show-5-details-img-4.png", id:4},{address:"/echo-show-5-details-img-5.png", id:5},{address:"/echo-show-5-details-img-6.png", id:6}, {address:"/echo-show-5-details.png", id:7} ],
        detailsImage:"/echo-show-5-details.png",
        reviews:[4,4,4,4,4], 
        reviewsAmount:"16,708", 
        firstPrice:"74", 
        lastPrice:"99", 
        totalPrice:74.99,
        availability:true,
        arrayNumber:5, 
    },
    {
        title:"Ring Video Doorbell",
        amount:0, 
        description:[ "1080p HD video doorbell with crisper Night Vision and features that let you see, hear, and speak to anyone from your phone or tablet.", "Answer the door from wherever you are with Two-Way Talk, or if you're busy, save time and use Quick Replies to respond with a pre-selected message.", "Receive instant notifications when anyone presses your doorbell or when motion is detected.", "Powered by the built-in rechargeable battery or connect it to your existing doorbell wires for constant power.","Easy installation: connect your Ring Video Doorbell to Wi-Fi through the Ring app and mount it to your wall with the included tools." ,"Pair with select Alexa-enabled devices and enable announcements to be notified when your doorbell is pressed or motion is detected." ,"Standard features such as instant notifications, live view and two-way talk are available out of the box and for free on all Ring devices. Add a Ring Protect Plan (subscription sold separately) to record, review and share the moment you missed (30-day free trial included in your purchase)."],
        id:87654,
        image:"/ring.png", 
        detailImages:[{address:"/ring-details-image.png", id:1},{address:"/ring-details-img-1.png", id:2},{address:"/ring-details-img-2.png", id:3}
        ,{address:"/ring-details-img-3.png", id:4},{address:"/ring-details-img-4.png", id:5},{address:"/ring-details-img-5.png", id:6}, {address:"/ring-details-img-6.png", id:7} ],
        detailsImage:"/ring-details-image.png",
        reviews:[4,4,4,4,4], 
        reviewsAmount:"41,180", 
        firstPrice:"89", 
        lastPrice:"99", 
        totalPrice:89.99,
        availability:true,
        arrayNumber:6, 
    },
    
    {
        title:"OraOral-B Precision Clean Electric Toothbrush Head with CleanMaximiser Technologyl",
        amount:0, 
        description:["With CleanMaximiser technology, green bristles turn yellow when it is time to replace your brush head", "Up to 100 Percent more plaque removal and healthier gums vs. a regular manual toothbrush", "The unique bristles brush away plaque for a superior tooth-by-tooth clean than with a regular manual toothbrush" , "Compatible with all Oral-B handles except Pulsonic & iO", "From the #1 brand recommended by dentists worldwide", "Number of toothbrush heads included in this pack: 12" ],
        id:77543,
        image:"/oral-b.png", 
        detailImages:[{address:"/oral-b-details-img-1.png", id:1},{address:"/oral-b-details-img-2.png", id:2},{address:"/oral-b-details-img-3.png", id:3}
        ,{address:"/oral-b-details-img-4.png", id:4},{address:"/oral-b-details-img-5.png", id:5}, {address:"/oral-b.png", id:6} ],
        reviews:[4,4,4,4], 
        reviewsAmount:"6,605", 
        firstPrice:"24", 
        lastPrice:"58",
        totalPrice:24.58, 
        availability:true,
    },
    {
        title:"Shure AONIC FREE True Wireless Earbuds, Sound Isolating Wireless Bluetooth Earphones, 21-Hr Battery Life",
        amount:0, 
        description:["CLEAR, DEEP BASS, STUDIO-QUALITY SOUND - Engineered from decades of experience developing products for music legends and performers of all kinds.", "SLEEK DESIGN, COMFORTABLE & SECURE FIT - Enjoy secure fit in a hook-free form factor that stays comfortably in place all day.", "DURABLE BUILT QUALITY - Durable quality that withstands sweat + the elements. Designed to pass rigorous quality and durability testing or long-lasting endurance.", "EASY ACCESS & CUSTOMIZABLE CONTROL - With the customizable button control you have quick access to volume, playback and calls.", "21 HOURS BATTERY LIFE – Up to 21 hours total battery life with pocketable carrying case for uninterrupted audio on-the-go. The earphones hold up to 7 hours of battery life per charge, and the slim, flip-top carrying case provides two additional charges.", "BLUETOOTH 5 TECHNOLOGY - Bluetooth 5 wireless technology for enhanced stability and a range of up to 30 feet (10 meters). Pairs to phones, tablets and laptops for music and calls.", "SOUND ISOLATING TECHNOLOGY – Naturally blocks up to 37 dB of noise to eliminate distractions noise and eliminates distractions. Enjoy the most immersive listening experience no matter where you are - on the train, in the gym, at the airport, or at home."],
        id:987764563,
        image:"/aonic-earbuds.png", 
        detailImages:[{address:"/aonic-earbuds.png", id:1},{address:"/shure-earbuds-details-img-1.png", id:2},{address:"/shure-earbuds-details-img-2.png", id:3}
        ,{address:"/shure-earbuds-details-img-3.png", id:4},{address:"/shure-earbuds-details-img-4.png", id:5}, {address:"/shure-earbuds-details-img-5.png", id:6},{address:"/shure-earbuds-details-img-6.png", id:7} ],
        reviews:[4,4,4,4], 
        reviewsAmount:"39", 
        firstPrice:"151", 
        lastPrice:"10", 
        totalPrice:151.10,
        availability:true,
    },
    {
        title:"Mens Trench Coat Lightweight Jacket Spring Autumn Short Windbreaker Outerwear",
        amount:0, 
        description:[`Size Guide(Chest): M - 44.88", L - 47.64", XL - 51.18", XXL - 54.72". For more measurement details please see the last image.`, "High Quality Fabric offers this Casual Jacket a fantastic wearing comfort. It's super soft and skin-friendly, warm meanwhile keeps you elegant.", "Collar Style: Turndown", "Long Sleeve", "Lightweight Outerwear with Cotton Lining. Perfect for Spring and Autumn. For Degree 15℃-20℃.", "Button Closure, Lapel Collar, Checked Lining, Long Sleeve, 2 Pockets, Medium Length, Plain/Solid Colour, Regular Fit. Fashionable and Classic.", "Short Trench Coat for Men. Meet both your Business and casual daily needs: Office Working, unofficial Meeting, Going Out for Dating, Vacation, Camping, Shopping, Walking etc. Great Gift for Birthday, Christmas, Valentine's Day or any other memory days."],
        id:10055109,
        image:"/coat-details.png",
        detailImages:[{address:"/coat-details.png", id:1},{address:"/coat-details-img-1.png", id:2},{address:"/coat-details-img-2.png", id:3}
        ,{address:"/coat-details-img-3.png", id:4},{address:"/coat-details-img-4.png", id:5},],
        detailsImage:"/coat-details.png" ,
        reviews:[4,4,4,4], 
        reviewsAmount:"3", 
        firstPrice:"35", 
        lastPrice:"99", 
        totalPrice:35.99,
        availability:true,
    },
    {
        title:"Under Armour Men's Ua Raid 8 Ultralight & Fast-Drying Workout Shorts for Men, Loose Sports Shorts with 4-Way Stretch",
        amount:0, 
        description:[, "Comfortable Shorts: Designed to be comfy and essential, these men's exercise shorts are ideal for sports, training, running, jogging and the gym", "Ultralight and Fast-Drying: Crafted from quick-drying material, the running shorts are incredibly light and prevent the build-up of perspiration", "Fastening: Lacing", "1257825", "4-Way Stretch Fabric: The men's gym shorts combine material with 4-way stretch technology to maintain free movement of the legs, hips and waist", "Modern Design: The sports shorts have two side pockets, an elastic waistband and SPF 30+ sun protection; They are ideal for modern, active men", "Material and Fit: Under Armour Raid 8 Men's Sports Shorts; Modern men's athletic shorts; Material: 90 Percent polyester and 10 Percent spandex; Fit: Loose"],
        id:7797344,
        image:"/shorts-details.png",
        detailImages:[{address:"/shorts-details.png", id:1},{address:"/shorts-details-img-1.png", id:2},{address:"/shorts-details-img-2.png", id:3}
        ,{address:"/shorts-details-img-3.png", id:4},{address:"/shorts-details-img-4.png", id:5},{address:"/shorts-details-img-5.png", id:6}],
        detailsImage:"/shorts-details.png" ,
        reviews:[4,4,4,4,4], 
        reviewsAmount:"6,263", 
        firstPrice:"25", 
        lastPrice:"09", 
        totalPrice:25.09,
        availability:true,
    },
    {
        title:"TRENDOUX Winter Gloves for Men and Women - Upgraded Touch Screen Anti-Slip Silicone Gel",
        amount:0, 
        description:[, "☛HIGH SENSITIVE TOUCHSCREEN: Featuring high sensitive conductive material on thumbs, forefingers and middle fingers, you can wear the gloves to touch screen of your smartphone, tablet, iPhone or other touch screen devices", "☛TRIANGLE SILICONE ANTI-SLIP: Fully covered with triangle silicone on palm, you can grip the steering wheel firmly when driving or hold your phone steadily without worrying about it slipping from your hand", "☛WARM LINING AND COMFORTABLE: Made of soft napping wool the inner lining, the gloves are extremely comfortable and warm considering they aren’t bulky! Also with the stretchy snug fit, you can type a text just as fast as you would without gloves", "☛WELL FITTING AND ELASTIC CUFF: Thickened elastic wrist keeps the glove closed around your skin and keeps the snow or wind out in winter. And the gloves are stretchy enough to fit your hands perfectly", "☛GOOD GIFT FOR YOUR FAMILY AND FRIENDS: These gloves are unisex and stretchy and have two sizes to choose, you can send one as a gift to your family or friends without worrying about the problem of size. They will love it very much"],
        id:909274,
        image:"/gloves.png",
        detailImages:[{address:"/gloves.png", id:1},{address:"/gloves-details-img-1.png", id:2},{address:"/gloves-details-img-2.png", id:3}
        ,{address:"/gloves-details-img-4.png", id:4},{address:"/gloves-details-img-5.png", id:5}],
        reviews:[4,4,4,4], 
        reviewsAmount:"25,275", 
        firstPrice:"10", 
        lastPrice:"19", 
        totalPrice:10.19,
        availability:true,
    },
    {
        title:"Amazon Essentials Men's Classic-Fit Expandable-Waist Flat-Front Dress Trouser",
        amount:0, 
        description:["Roomy through hip & thigh with straight leg. Sits at the waist", "Silky smooth and movable twill polyester fabric", "Fastening: Button", "Expandable Waist Classic-Fit Flat-Front Dress PantsRegular", "MAE65002SP18"],
        id:70927845,
        image:"/trousers-details.png",
        detailImages:[{address:"/trousers-details.png", id:1},{address:"/trousers-details-img-1.png", id:2},{address:"/trousers-details-img-2.png", id:3}
        ,{address:"/trousers-details-img-3.png", id:4},{address:"/trousers-details-img-4.png", id:5}, {address:"/trousers-details-img-5.png", id:6} ],
        detailsImage:"/trousers-details.png" ,
        reviews:[4,4,4,4], 
        reviewsAmount:"8,938", 
        firstPrice:"25", 
        lastPrice:"40", 
        totalPrice:25.40,
        availability:true,
    },
    {
        title:"I Have Something to Tell You: The most thought-provoking, captivating fiction novel of 2021 from bestselling author Susan Lewis",
        amount:0, 
        description:[ "High-flying lawyer Jessica Wells has it all. A successful career, loving husband Tom and a family she adores. But one case – and one client – will put all that at risk.", "Edward Blake. An ordinary life turned upside down – or a man who quietly watched television while his wife was murdered upstairs? With more questions than answers and a case too knotted to unravel, Jessica suspects he’s protecting someone.", "Then she comes home one day and her husband utters the words no one ever wants to hear. Sit down … I have something to tell you", "Now Jessica must fight not only for the man she defends, but for the man she thought she trusted with her life – her husband.", "Look out for the latest thrilling book from the Sunday Times bestselling author – available to pre-order now!"],
        id:88675443,
        image:"/susan-lewis.png",
        detailImages:[{address:"/susan-lewis.png", id:1}], 
        detailsImage:"/susan-lewis.png" ,
        reviews:[4,4,4,4,4], 
        reviewsAmount:"3,196", 
        firstPrice:"2", 
        lastPrice:"99", 
        totalPrice:2.99,
        availability:true,
    },
    {
        title:"The Keeper of Stories: NEW for 2022, the most charming and uplifting novel you will read this year!",
        amount:0, 
        description:["‘A treasure of a book. Beautiful, emotional and heartfelt with a cornucopia of characters you’ll love spending time with’ Phaedra Patrick, author of The Library of Lost and Found", "She can’t recall what started her collection. Maybe it was in a fragment of conversation overheard as she cleaned a sink? Before long (as she dusted a sitting room or defrosted a fridge) she noticed people were telling her their stories. Perhaps they always had done, but now it is different, now the stories are reaching out to her and she gathers them to her…", "When Janice starts cleaning for Mrs B – a shrewd and tricksy woman in her nineties – she meets someone who wants to hear her story. But Janice is clear: she is the keeper of stories, she doesn’t have a story to tell. At least, not one she can share", "Mrs B is no fool and knows there is more to Janice than meets the eye. What is she hiding? After all, doesn’t everyone have a story to tell?"],
        id:256338450,
        image:"/the-keeper-of-stories.png",
        detailImages:[{address:"/the-keeper-of-stories.png", id:1}], 
        detailsImage:"/the-keeper-of-stories.png" ,
        reviews:[4,4,4,4,4], 
        reviewsAmount:"1,357", 
        firstPrice:"2", 
        lastPrice:"99", 
        totalPrice:2.99,
        availability:true,
    },
    {
        title:"The Four Winds: The Internationally Bestselling Richard & Judy Book Club Pick",
        amount:0, 
        description:[ "'A story of love, family, unbreakable bonds, bravery and hope. I loved this book so much!' - Christy Lefteri, author of The Beekeeper of Aleppo", "Texas, 1934. Elsa Martinelli had finally found the life she’d yearned for. A family, a home and a livelihood on a farm on the Great Plains. But when drought threatens all she and her community hold dear, Elsa’s world is shattered to the winds.", "Fearful of the future, when Elsa wakes to find her husband has fled, she is forced to make the most agonizing decision of her life. Fight for the land she loves or take her beloved children, Loreda and Ant, west to California in search of a better life. Will it be the land of milk and honey? Or will their experience challenge every ounce of strength they possess?", "From the overriding love of a mother for her child, the value of female friendship and the ability to love again – against all odds – Elsa’s incredible journey is a story of survival, hope and what we do for the ones we love.", "The Four Winds is a deeply moving, powerful story about the strength and resilience of women and the bond between mother and daughter, by the multi-million-copy number one bestselling author of The Nightingale, Kristin Hannah."],
        id:77790976443,
        image:"/the-four-winds.png",
        detailsImage:"/the-four-winds.png" ,
        detailImages:[{address:"/the-four-winds.png", id:1}], 
        reviews:[4,4,4,4,4], 
        reviewsAmount:"59,558", 
        firstPrice:"3", 
        lastPrice:"99", 
        totalPrice:3.99,
        availability:true,
    },
    {
        title:"Spring: 'A dazzling hymn to hope’ Observer (Seasonal Quartet Book 3)",
        amount:0, 
        description:[ "THE SUNDAY TIMES NUMBER ONE BESTSELLER", "Discover Ali Smith's dazzling, once-in-a-generation series, the Seasonal Quartet, a tour-de-force quartet of novels about love, time, art, politics, and how we live right now", "All four instalments of the quartet are available to buy and read in paperback and ebook now: Autumn, Winter, Spring and Summer", "'Her best yet, a dazzling hymn to hope, uniting the past and present with a chorus of voices . . . [Ali Smith] is lighting us a path out of the nightmarish now' - Observer", "What unites Katherine Mansfield, Charlie Chaplin, Shakespeare, Rilke, Beethoven, Brexit, the present, the past, the north, the south, the east, the west, a man mourning lost times, a woman trapped in modern times?", "Spring. The great connective.", "With an eye to the migrancy of story over time, and riffing on Pericles, one of Shakespeare's most resistant and rollicking works, Ali Smith tells the impossible tale of an impossible time. In a time of walls and lockdown Smith opens the door.", "The time we're living in is changing nature. Will it change the nature of story?"],
        id:134577888432234,
        image:"/spring.png",
        detailImages:[{address:"/spring.png", id:1}], 
        detailsImage:"/spring.png" ,
        reviews:[4,4,4,4,4], 
        reviewsAmount:"622", 
        firstPrice:"4", 
        lastPrice:"99", 
        totalPrice:4.99,
        availability:true,
    },
    
    ]} 