import Head from 'next/head'
import { Fragment } from 'react'
import HomePage from "../components/HomePage"


import { appContext} from './_app'

export default function Home() {

  return (

    <Fragment>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage key={Math.random()}/>

    </Fragment>
  )
}